name: ci

on:
  push:
    paths:
      - '**.cpp'
      - '**.c'
      - '**.py'
      - '**.cmake'
      - 'CMakeLists.txt'

jobs:

  windows-vs2026:
    runs-on: windows-2025-vs2026

    strategy:
      fail-fast: false
      matrix:
        arch: [x64, arm64]

    steps:
      - &checkout
        uses: actions/checkout@v6

      - name: Configure CMake
        run: cmake -Bbuild -A ${{ matrix.arch }} -G "Visual Studio 18 2026"

      - &build-release
        name: Build
        run: cmake --build build --config Release

        # Prism is only for x64 on arm64 CPU, not the other way around
      - &test-x64
        name: Test
        if: matrix.arch == 'x64'
        run: ctest --test-dir build -V -C Release

  windows:
    runs-on: windows-2025

    strategy:
      fail-fast: false
      matrix:
        arch: [x64, arm64]

    steps:
      - *checkout

      - name: Configure CMake
        run: cmake -Bbuild -A ${{ matrix.arch }}

      - *build-release

      # Prism is only for x64 on arm64 CPU, not the other way around
      - *test-x64

  macos:
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, arm64]

    steps:
      - *checkout

      - name: Configure CMake
        run: cmake -Bbuild -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }}

      - name: Build
        run: cmake --build build

      - name: Test
        run: ctest --test-dir build -V
