name: ci

on:
  push:

jobs:

  windows-vs2026:
    runs-on: windows-2025-vs2026

    strategy:
      fail-fast: false
      matrix:
        arch: [x64, arm64]

    steps:
      - uses: actions/checkout@v6

      - name: Configure CMake
        run: cmake -Bbuild -A ${{ matrix.arch }} -G "Visual Studio 18 2026"

      - name: Build
        run: cmake --build build --config Release

        # Prism is only for x64 on arm64 CPU, not the other way around
      - name: Test
        if: matrix.arch == 'x64'
        run: ctest --test-dir build -V -C Release

  windows:
    runs-on: windows-2025

    strategy:
      fail-fast: false
      matrix:
        arch: [x64, arm64]

    steps:
      - uses: actions/checkout@v6

      - name: Configure CMake
        run: cmake -Bbuild -A ${{ matrix.arch }}

      - name: Build
        run: cmake --build build --config Release

      # Prism is only for x64 on arm64 CPU, not the other way around
      - name: Test
        if: matrix.arch == 'x64'
        run: ctest --test-dir build -V -C Release

  macos:
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, arm64]

    steps:
      - uses: actions/checkout@v6

      - name: Configure CMake
        run: cmake -Bbuild -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }}

      - name: Build
        run: cmake --build build

      - name: Test
        run: ctest --test-dir build -V
